### ISSUE TITLE
Issue with Subject-level MEAN transformations of non-decision time

### ISSUE THREAD

**Issue by dkatsimpokis** [Seneketh/StanDDM#3]
There is an issue in the Subject-level MEAN transformations of the non-decision time parameter (NDT) in the DDM. I discovered it when working with the file _StanDDM_NCEN_St.r_ that fits the DDM with trial-to-trial variability in the NDT. Specifically, the loop (line 71) does not adjust the NDT based on each participant's _minRT_ because the index in the _minRT_ variable is _N_ and not _i_. Here is the code:

`tau_mu[i]  = Phi_approx(mu_mu[4] + mu_sigma[4] * tau_mu_pr[i]) * (minRT[N]-RTbound) + RTbound;`

This code adjusts NDT only based on the last participant's minRT. I think the code should be something like that:

`tau_mu[i]  = Phi_approx(mu_mu[4] + mu_sigma[4] * tau_mu_pr[i]) * (minRT[i]-RTbound) + RTbound;`

I have checked and I found out that the issue is in every model implementation not just in the one with trial-to-trial NDT variability.

**Comment by mar-wir** [comment]
Hey @dkatsimpokis !

Many thanks for taking the time to actually check the code and contribute!

The adjustment of the  `minRT` via the `RTbound` is a necessary evil because of the finicky Wiener likelihood implemented in Stan.  It is surprising that it even worked in the current state ( ᐛ )و . I guess only very extreme cases would cause the sampling to break?

The change you suggest is of course completely warranted. Can you create a pull request for the change?

**Comment by mar-wir** [comment]
Fixed
